package com.agent.core.rag.tool;

import com.agent.core.agent.code.Py4jGateway;
import com.agent.core.rag.RagService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

import java.util.Map;

/**
 * RAG Knowledge Search Tool registered with Py4jGateway.
 *
 * Exposes RAG retrieval as a toolkit that LLM-generated Python code can invoke:
 * <pre>
 * # Python code generated by LLM
 * result = knowledgeBase.search(query="发布单卡住怎么办", tenantId="default")
 * </pre>
 *
 * Supports two methods:
 * <ul>
 *   <li>{@code search} — retrieve context only (for prompt injection)</li>
 *   <li>{@code query} — full RAG pipeline with LLM summarization</li>
 * </ul>
 */
@Slf4j
@Component
@RequiredArgsConstructor
public class KnowledgeSearchTool implements Py4jGateway.ToolkitHandler {

    private static final String TOOLKIT_NAME = "knowledgeBase";

    private final RagService ragService;

    /**
     * Get the toolkit name used for registration.
     */
    public String getToolkitName() {
        return TOOLKIT_NAME;
    }

    /**
     * Get the Python class stub for LLM prompt injection.
     * This tells the LLM what methods are available.
     */
    public String getPythonStub() {
        return """
                class knowledgeBase:
                    \"\"\"知识库检索工具。用于在私域知识库中搜索相关文档。\"\"\"
                    
                    @staticmethod
                    def search(query: str, tenantId: str = "default") -> str:
                        \"\"\"检索知识库并返回相关上下文片段（不含LLM总结）。
                        Args:
                            query: 用户的问题
                            tenantId: 租户ID，默认为 "default"
                        Returns:
                            检索到的知识上下文字符串
                        \"\"\"
                        pass
                    
                    @staticmethod
                    def query(query: str, tenantId: str = "default") -> dict:
                        \"\"\"完整RAG问答：检索知识库 + LLM生成回答。
                        Args:
                            query: 用户的问题
                            tenantId: 租户ID，默认为 "default"
                        Returns:
                            包含 answer、subQueries、retrievedCount 等字段的字典
                        \"\"\"
                        pass
                """;
    }

    @Override
    public Object invoke(String methodName, Map<String, Object> args) {
        String query = (String) args.get("query");
        String tenantId = (String) args.getOrDefault("tenantId", "default");

        if (query == null || query.isBlank()) {
            throw new IllegalArgumentException("query parameter is required");
        }

        log.info("KnowledgeSearchTool invoked: method='{}', query='{}', tenant='{}'",
                methodName, query, tenantId);

        return switch (methodName) {
            case "search" -> ragService.retrieveContext(query, tenantId);
            case "query" -> {
                RagService.RagResult result = ragService.query(query, tenantId);
                yield Map.of(
                        "answer", result.getAnswer(),
                        "subQueries", result.getSubQueries(),
                        "retrievedCount", result.getRetrievedCount(),
                        "rerankedCount", result.getRerankedCount(),
                        "durationMs", result.getDurationMs()
                );
            }
            default -> throw new IllegalArgumentException("Unknown method: " + methodName
                    + ". Available methods: search, query");
        };
    }
}
